annotations:
  licenses: MIT NON-AI

apiVersion: v2
name: bc-wallet-common-mgrtr
description: A Helm chart for Kubernetes

type: library
keywords:
  - crypto-bundle
  - cryptobundle
  - infrastructure
  - database
  - migration
  - migrator

version: 0.0.1
appVersion: 0.0.5